### ISSUE TITLE
Error using content_for on test environment

### ISSUE THREAD

**Issue by badosu** [jeremyevans/roda#53]
After upgrading Roda to 2.8.0 I've been receiving the following error on my test suite, this happens when calling `content_for` with a block, my engine is Slim:

```
NoMethodError: undefined method `encoding' for nil:NilClass
    /home/badosu/.gem/ruby/2.2.3/gems/temple-0.7.6/lib/temple/filters/remove_bom.rb:8:in `call'
    /home/badosu/.gem/ruby/2.2.3/gems/temple-0.7.6/lib/temple/engine.rb:50:in `block in call'
    /home/badosu/.gem/ruby/2.2.3/gems/temple-0.7.6/lib/temple/engine.rb:50:in `each'
    /home/badosu/.gem/ruby/2.2.3/gems/temple-0.7.6/lib/temple/engine.rb:50:in `inject'
    /home/badosu/.gem/ruby/2.2.3/gems/temple-0.7.6/lib/temple/engine.rb:50:in `call'
    /home/badosu/.gem/ruby/2.2.3/gems/temple-0.7.6/lib/temple/mixins/template.rb:10:in `compile'
    /home/badosu/.gem/ruby/2.2.3/gems/temple-0.7.6/lib/temple/templates/tilt.rb:30:in `prepare'
    /home/badosu/.gem/ruby/2.2.3/gems/tilt-2.0.1/lib/tilt/template.rb:87:in `initialize'
    /home/badosu/.gem/ruby/2.2.3/gems/roda-2.8.0/lib/roda/plugins/content_for.rb:41:in `new'
    /home/badosu/.gem/ruby/2.2.3/gems/roda-2.8.0/lib/roda/plugins/content_for.rb:41:in `content_for'
```

Any idea what could it be?

**Comment by jeremyevans** [comment]
This appears to be a bug in temple.  It's expect a string argument but receiving a nil argument.  Looks like an issue somewhere in the temple call_chain.  Unfortunately, I don't have any experience with temple.  Could you put together a self contained reproducible example that works with Roda 2.7.0 and fails with Roda 2.8.0?

**Comment by badosu** [comment]
Hm... this could have been cause by the temple upgrade then... I'll investigate this issue further soon.

**Comment by jeremyevans** [comment]
@badosu I'm going to close this now.  If you find that this was due to a problem with Roda, please submit a test case that works on Roda 2.7.0 and fails on Roda 2.8.0 and I'll reopen.

**Comment by badosu** [comment]
@jeremyevans Gotcha
